name: dragonboard-builder
version: "0.5.2"
summary: ubuntu core fastboot compatible image buider
description: |
 toolset to build emmc ubuntu core images for dragonboard flashable with fastboot

confinement: strict
grade: stable

environment:
    PATH:            $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
    LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}"
base: core18
layout:
  /etc/mke2fs.conf:
    bind-file: $SNAP_COMMON/etc/mke2fs.conf
  /etc/mtools.conf:
    bind-file: $SNAP_COMMON/etc/mtools.conf

apps:
    build-uc-image:
        command: usr/bin/fakeroot-sysv -- build-uc-image
        plugs:
            - home
            - mount-observe
            - network-observe
            - ssh-public-keys
        adapter: none

parts:
  tools:
    plugin: nil
    stage-packages:
      - e2fsprogs
      - libfdisk1
      - libuuid1
      - libblkid1
      - libcomerr2
      - libudev1
      - zlib1g
      - liblzma5
      - e2fslibs
      - img2simg
      - simg2img
      - android-libsparse
      - mtools
      - squashfs-tools
      - dosfstools
      - gdisk
      - fakeroot
    override-build: |
      sed -i \
          -e 's|/usr/lib/|${SNAP}/usr/lib/|g' \
          -e 's|FAKEROOT_PREFIX=|FAKEROOT_PREFIX=${SNAP}|g' \
          -e 's|FAKEROOT_BINDIR=|FAKEROOT_BINDIR=${SNAP}|g' \
          ${SNAPCRAFT_PART_INSTALL}/usr/bin/fakeroot-sysv
      ln -sf fakeroot-sysv ${SNAPCRAFT_PART_INSTALL}/usr/bin/fakeroot

  glue:
    plugin: dump
    source: glue

  snap-client:
    plugin: nil
    override-build: |
      snap download snapd --edge
      unsquashfs -f -d ${SNAPCRAFT_PART_INSTALL} snapd*.snap usr/bin/snap

