name: dragonboard-builder
version: "0.1.6"
summary: ubuntu core fastboot compatible image buider
description: |
 toolset to build emmc ubuntu core images for dragonboard flashable with fastboot

confinement: strict
grade: stable

environment:
    PATH:            $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
    LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}"
base: core18
layout:
  /etc/mke2fs.conf:
    bind-file: $SNAP_COMMON/etc/mke2fs.conf
  /etc/mtools.conf:
    bind-file: $SNAP_COMMON/etc/mtools.conf

apps:
    build-uc-image:
        command: bin/build-uc-image
        plugs:
            - home
            - mount-observe
            - network-observe
        adapter: none

parts:
  tools:
    plugin: nil
    stage-packages:
      - libc6
      - libc-bin
      - e2fsprogs
      - libfdisk1
      - libuuid1
      - libblkid1
      - libcomerr2
      - libudev1
      - zlib1g
      - liblzma5
      - e2fslibs
      - img2simg
      - simg2img
      - android-libsparse
      - mtools
      - squashfs-tools
      - dosfstools
      - gdisk

  glue:
    plugin: dump
    source: glue

  snap-client:
    plugin: nil
    override-build: |
      [ ! -d /snap/core ] && snap install core
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      cp /snap/core/current/usr/bin/snap ${SNAPCRAFT_PART_INSTALL}/usr/bin

