name: dragonboard-builder
version: "0.0.4"
summary: ubuntu core dragonboard fastboot compatible image buider
description: |
 toolset to build emmc ubuntu core images for dragonboard flashable with fastboot

confinement: strict
passthrough:
grade: stable

passthrough:
  base: core18
  layout:
    /etc/mke2fs.conf:
      bind-file: $SNAP_COMMON/etc/mke2fs.conf
    /etc/mtools.conf:
      bind-file: $SNAP_COMMON/etc/mtools.conf

apps:
    build-db410c-image:
        command: bin/build-db410c
        plugs: [home, mount-observe, network-observe ]
        adapter: none
        environment:
            PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:SNAP_LIBRARY_PATH

parts:
  e2fsprogs:
    plugin: nil
    stage-packages:
      - libc6
      - libc-bin
      - e2fsprogs
      - libfdisk1
      - libuuid1
      - libblkid1
      - libcomerr2
      - libudev1
      - zlib1g
      - liblzma5
      - e2fslibs
      - img2simg
      - simg2img
      - android-libsparse
      - mtools
      - squashfs-tools
      - dosfstools

  scripts:
    plugin: dump
    source: bin
    organize:
      '*' : bin/

  snap-client:
    plugin: nil
    override-build: |
      [ ! -d /snap/core ] && snap install core
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      cp /snap/core/current/usr/bin/snap ${SNAPCRAFT_PART_INSTALL}/usr/bin
